kind: Pod
apiVersion: v1
metadata:
  name: nodelabel
spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash", "-c" ,"while true ; do echo Hello-Hari ; sleep 5 ; done"]



  nodeSelector:                       #Specify which node to run the pod
       mynode: saidemy                #can give anything

