kind: Pod
apiVersion: v1
metadata:
  name: levelspod2
  labels:                     #Specifies the level details under it
     days: sat                # <Keyname1> : <Value>
     class: kubernetes        # <Keyname2> : <Value>


spec:
  containers:
    - name: c00
      image: ubuntu
      command: ["/bin/bash", "-c", "while true; do echo Hello-Rahul ; sleep 5; done"]

