kind: ReplicaSet            #Define the object to be ReplicaSet
apiVersion: apps/v1         #ReplicaSet is not available on v1
metadata:
  name: myreplicaset
spec:
  replicas: 2              #This element defines the desired number pods
  selector:                #Tells the controller which pod to watch/belong to this Replication Set
   matchExpressions:        #These must match the labels 
    - {key: myname, operator: In, values: [hari, harii,hariii]}     # - {key: env, operator:NotIn, values:[production]}

  template:              #template element defines a template to lunch a new pod
    metadata:
      labels:            #Selector values need to match the labels values specified in the pod template
        myname: hari
    spec:
      containers:
        - name: c00
          image: ubuntu
          command: ["/bin/bash", "-c" ,"while true ; do echo Hello-Rahul ; sleep 5 ; done"]
